[project]
name = "multimodel-ai-system"
version = "0.1.0"
description = "Multi-Model AI System root workspace"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "flask==2.3.3",
    "requests",
    "python-dotenv==1.0.0",
    "flask-cors==4.0.0",
    "google-genai",
    "flask-pymongo<3.0",
    "dnspython",
    "flask-bcrypt",
    "flask-jwt-extended",
    "pypdf",
    "gtts",
    "pillow",
]
